services:
  - type: web
    name: psytech-agora
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_REMETENTE
        sync: false
      - key: EMAIL_SENHA
        sync: false
